name: Docker Image CI

on:
  push:
    branches:
      - develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
    - uses: action/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile
      run: mvn -B compile
    - name: Run Tests
      run: mvn -B test
    - name: Package
      run: mvn -B package
      
      
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag quick-list-server:latest-unstable
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
