name: Docker Image CI

on:
  push:
    branches:
      - develop

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
    - uses: action/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile
      run: mvn -B compile